### ISSUE TITLE
[ESC] doesn't close widget if has not the focus

### ISSUE THREAD

**Issue by Fred-Vatin** [spywhere/vscode-mark-jump#4] opened 2017-06-11 14:34 UTC
VS Code version | OS | Extension version
------------------ | ---- | ----
1.13.0  | Win x64 pro (french) | 0.3.1

Well everything is in the title. I can only close the widget with [ESC] key if it has focus. If focus is on the editor, it won't work.

**Comment by spywhere** [comment] 2017-06-11 15:37
That's expectable. Without focus lock, switch to a new mark will also cause the widget to close too. I'll leave this as an enhancement (customizable options) as this is not a bug.

**Comment by spywhere** [comment] 2017-06-13 17:13
I think I got what you mean by this. Mark Jump widget can only be closed when press `ESC` while it has focus. However, when jump to the mark itself, its focus is move to the editor, making it uneasy to close the widget.

The above issue have been fixed in v0.4.0. Please feel free to reopen the issue if you think this is not the issue you have.

**Closed as completed by spywhere** 2017-06-13 17:13 UTC
Labels: bug
